development:
  adapter: postgresql
  database: jsoverflow_dev
  encoding: utf8
  pool: 5
  timeout: 5000
  host: localhost

test:
  adapter: postgresql
  database: jsoverflow_test
  encoding: utf8
  pool: 5
  timeout: 5000
  host: localhost

production:
  adapter: postgresql
  database: jsoverflow_production
  encoding: utf8
  pool: 5
  timeout: 5000
  host: localhost
